[book]
authors = ["matchy233"]
language = "zh"
multilingual = true
src = "src"
title = "Random Notes"

[output.html]
mathjax-support = true
default-theme = "Rust"
preferred-dark-theme = "Ayu"
additional-css = ["theme/custom.css"]

[output.html.fold]
enable = true
level = 0
